version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: "gonza-lab2-frontend"
    CONTAINER_NAME: "frontend"          # (1) agregar
phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - ECR_REPO=$ECR_REGISTRY/$IMAGE_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - docker build -t $ECR_REPO:$IMAGE_TAG ./app
      - docker push $ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json   # (2)
artifacts:
  files:
    - imagedefinitions.json
