services:
  mysql:
    build: .
    container_name: mysql-clase
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: mi_base
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: ./app
    container_name: app-clase
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: mi_base
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
